# Generated by Django 4.0.5 on 2022-06-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False, verbose_name='is_admin')),
                ('is_user', models.BooleanField(default=False, verbose_name='is_user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
